# Generated by Django 5.2.6 on 2025-09-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_alter_student_birth_city_alter_student_birth_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='requirement_agreement',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
