# Generated by Django 5.2.6 on 2025-09-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_student_enrollment_chance_student_entry_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='requirement_agreement',
            field=models.CharField(default=False, null=True),
        ),
    ]
