# Generated by Django 5.2.6 on 2025-09-18 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_alter_student_requirement_agreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
    ]
