# Generated by Django 5.2.6 on 2025-09-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_remove_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='requirement_agreement',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
