# Generated by Django 5.2.6 on 2025-09-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_alter_student_requirement_agreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrollment_chance',
        ),
        migrations.RemoveField(
            model_name='student',
            name='entry_level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='student',
            name='suffix',
        ),
        migrations.AlterField(
            model_name='student',
            name='campus_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
