# Generated by Django 5.2.6 on 2025-09-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_alter_student_requirement_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='annual_income',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
